- block:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
  rescue:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/latest/vector_latest-1_amd64.deb"
        dest: "/tmp/vector_latest-1_amd64.deb"
- block:
    - name: Install vector packages
      apt:
        deb: /tmp/vector_{{ vector_version }}-1_amd64.deb
      become: true
      become_method: sudo
  rescue:
    - name: Install vector packages
      apt:
        deb: /tmp/vector_latest-1_amd64.deb
      become: true
      become_method: sudo